#!/bin/bash
#set -x

# Check this out and add the following to your .profile
# source <PATH_TO_HERE>/profile_common

#. "$HOME/.cargo/env"

GO_HOME=`ls -d $HOME/.asdf/installs/golang/*/go`

# the bash in /usr/local/bin is not arm64, see
# https://github.com/orgs/Homebrew/discussions/2486#discussioncomment-1662525 
# add brew to path before local bin to get arm64 not x86_64
export PATH=/bin:/opt/homebrew/bin:/usr/bin:/usr/local/bin
export PATH=/opt/homebrew/opt/python@3.11/libexec/bin:$PATH
export PATH=$GO_HOME/bin:$PATH
export PATH=$PATH:$PATH:$HOME/bin:$COMMON_BIN
# for cursor aegnt
export PATH="$HOME/.local/bin:$PATH"
export EDITOR=vi
export AIRFLOW_HOME=$HOME/src/airflow_dags

THIS_DIR=`dirname "${BASH_SOURCE[0]}"`
COMMON_BIN=$THIS_DIR/bin


# see http://m.onkey.org/if-you-see-this
source $COMMON_BIN/git-ps1.sh
source $COMMON_BIN/git-completion.bash

GOPATH=$GO_HOME/bin/go
PATH=$PATH:$HOME/src/shell_env/bin

PATH=$PATH:/Applications/TextMate.app/Contents/MacOS
PATH=$PATH:$HOME/Library/Python/3.9/bin

PATH=$PATH:$HOME/.cargo/bin
#PATH=$PATH:$(go env GOPATH)/bin
PATH=$PATH:/Applications/SnowSQL.app/Contents/MacOS

for bcfile in /usr/local/etc/bash_completion.d/*; do
    [ -f "$bcfile" ] && [[ "$bcfile" != "/usr/local/etc/bash_completion.d/ctest" ]] && . "$bcfile"
done

# terraform -install-autocomplete

# alias go="go1.21.5"
alias gitc='git checkout'
alias gitcm='if [ `git rev-parse --verify main  2> /dev/null` ]; then git checkout main; else git checkout master; fi'
alias gitcd="git checkout develop"
alias gits="git status"
alias gitb="git branch"

# git autocomplete
complete -o default -W "\$(git branch 2>/dev/null | cut -c 3-)" git
complete -o default -W "\$(git branch 2>/dev/null | cut -c 3-)" gitb
complete -o default -W "\$(git branch 2>/dev/null | cut -c 3-)" gitc

# kubectl autocompletion
# See https://komodor.com/learn/kubectl-autocomplete-enabling-and-using-in-bash-zsh-and-powershell/
if [ -f /opt/homebrew/etc/bash_completion ]; then
. /opt/homebrew/etc/bash_completion
fi
source <(kubectl completion bash)
	
# should start using sdkman https://sdkman.io/usage#use
use-java () {
  version=$1
  if (( $version < 9 )); then
    version=1.$version
  fi
  export JAVA_HOME=`/usr/libexec/java_home -v $version`
}

# for global pip installs that don't go into virtualenv.
# see https://hackercodex.com/guide/python-development-environment-on-mac-osx/
gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip3 "$@"
}

VE=""
if [ -n "$VIRTUAL_ENV" ]; then
  VE="(`basename $VIRTUAL_ENV`)"
fi
PS1='$VE[\u@\h \w$(git-ps1 " (%s)")]\$ '
